name: Action CI

on:
  push:
    tags:
      - "*"

concurrency: new-tag
jobs:
  release:
    name: GitHub Release
    runs-on: ubuntu-latest
    steps:
      - id: semver-checkout
        name: Checkout
        uses: EasyDesk/action-semver-checkout@v1
      - name: Release
        if: ${{ steps.semver-checkout.outputs.should-release == 'true' }}
        uses: ./
        with:
          version: ${{ steps.semver-checkout.outputs.version }}
          prerelease: ${{ steps.semver-checkout.outputs.is-github-prerelease }}
          
